## Scalars, Vectors and Matrics

In [4]:
import numpy as np

### Scalars

In [1]:
s = 5

In [2]:
s

5

### Vector

In [5]:
v = np.array([5,-2,4])

In [6]:
v

array([ 5, -2,  4])

### Matrices

In [7]:
m = np.array([[5,12,6],[-3,0,14]])

In [8]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data types

In [9]:
type(s)

int

In [10]:
type(v)

numpy.ndarray

In [11]:
type(m)

numpy.ndarray

In [12]:
s_array = np.array(5)
s_array

array(5)

In [13]:
type(s_array)

numpy.ndarray

### Data shapes

In [14]:
m.shape

(2, 3)

In [15]:
v.shape

(3,)

In [19]:
s_array.shape

()

### Creating a column vector

In [17]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [18]:
#row vector
v.reshape(1,3)

array([[ 5, -2,  4]])

### Creating a tensor

In [21]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [20]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [22]:
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

### Checking its shape

In [23]:
t.shape

(2, 2, 3)

In [ ]:
### Manually creating a tensor

In [24]:
t_manual = np.array([[[5, 12, 6], [-3, 0, 14]],[[9, 8, 7], [1, 3, 5]]])

In [25]:
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3,  5]]])

## Matrix addition

In [26]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

## Matrix subtraction

In [28]:
m3 = np.array([[5,3],[-2,4]])
m4 = np.array([[7,-5],[3,8]])

In [29]:
m3-m4

array([[-2,  8],
       [-5, -4]])

In [30]:
m5 = np.array([[22.33, -4.73],[-203.14,1200.02],[4.22,234.10]])
m5

array([[  22.33,   -4.73],
       [-203.14, 1200.02],
       [   4.22,  234.1 ]])

In [31]:
m6 = np.array([[131.13,448.29],[-340.21,1.06],[30.41,424.99]])
m6

array([[ 131.13,  448.29],
       [-340.21,    1.06],
       [  30.41,  424.99]])

In [32]:
m5-m6

array([[-108.8 , -453.02],
       [ 137.07, 1198.96],
       [ -26.19, -190.89]])

## Exceptions (addition with a scalar)

In [34]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [35]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [37]:
v

array([ 5, -2,  4])

In [38]:
v + 1

array([ 6, -1,  5])

In [39]:
m1 + np.array([1])

array([[ 6, 13,  7],
       [-2,  1, 15]])

## Transposing matrices

In [40]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [41]:
m1.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [42]:
m3

array([[ 5,  3],
       [-2,  4]])

In [43]:
m3.T

array([[ 5, -2],
       [ 3,  4]])

## Transposing vectors

In [45]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [46]:
x.T

array([1, 2, 3])

In [47]:
x.shape

(3,)

In [48]:
x_reshaped = x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [50]:
x_reshaped.T

array([[1],
       [2],
       [3]])

## Dot product

In [51]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [52]:
np.dot(x,y)

-66

In [53]:
u = np.array([0,2,5,8])
v = np.array([20,3,4,-1])

In [54]:
np.dot(u,v)

18

### scalar* scalar

In [55]:
np.dot(5,6)

30

### scalar*vector

In [56]:
x

array([ 2,  8, -4])

In [57]:
5*x

array([ 10,  40, -20])

### scalar*matrix

In [60]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [61]:
3*m1

array([[15, 36, 18],
       [-9,  0, 42]])

In [64]:
b = np.array([[2,-1],[8,0],[3,0]])
b

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [65]:
np.dot(m1,b)

array([[124,  -5],
       [ 36,   3]])